#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Translates hardcoded Russian UI strings to English across the SA-MP client source.
Run this from the ROOT of your project folder (where app/ lives):
    python3 translate.py
It walks app/src/main/java and rewrites every .kt/.java file in place,
doing an exact literal replace for every string below (no regex, no risk
of partial/garbled matches).
A backup of every changed file is saved alongside it with a .bak extension,
so you can always revert manually if something looks wrong.
"""

import os

ROOT = "app/src/main/java"

TRANSLATIONS = {
    "км/ч": "km/h",
    "руб.": "rub.",
    "с.": "sec.",
    "$myPlaceByLvl место": "$myPlaceByLvl place",
    "$myPlaceByPoints место": "$myPlaceByPoints place",
    "$timeInMinutes мин.": "$timeInMinutes min.",
    "%d игроков": "%d players",
    "%d из %d": "%d of %d",
    "%d руб.": "%d rub.",
    "%d секунд": "%d seconds",
    "%d фишек": "%d chips",
    "%s из %s (%s / сек.)": "%s of %s (%s / sec.)",
    "%s л": "%s L",
    "%s руб.": "%s rub.",
    "%sр/литр": "%s rub/liter",
    "+1 слот для авто": "+1 vehicle slot",
    "+100 законопослушность": "+100 Law-Abiding Score",
    "0 л": "0 L",
    "0 р": "0 rub",
    "1 = 1.000 руб.": "1 = 1,000 rub.",
    "1 = 950 руб.": "1 = 950 rub.",
    "1.111 фишек": "1,111 chips",
    "1.111.111 руб.": "1,111,111 rub.",
    "11.000 фишек": "11,000 chips",
    "11.000.000 руб.": "11,000,000 rub.",
    "150 фишек": "150 chips",
    "150.000 руб.": "150,000 rub.",
    "200 фишек": "200 chips",
    "200.000 руб.": "200,000 rub.",
    "3.500 фишек": "3,500 chips",
    "3.500.000 руб.": "3,500,000 rub.",
    "4-х значный номер": "4-digit number",
    "5.250.000 руб.": "5,250,000 rub.",
    "5.300 фишек": "5,300 chips",
    "5.500 фишек": "5,500 chips",
    "5.500.000 руб.": "5,500,000 rub.",
    "520 фишек": "520 chips",
    "520.000 руб.": "520,000 rub.",
    "<b>Формат номера:</b><br>1234 АВ-5": "<b>Plate format:</b><br>1234 AB-5",
    "<b>Формат номера:</b><br>123АВС 12": "<b>Plate format:</b><br>123ABC 12",
    "<b>Формат номера:</b><br>А123ВС 45": "<b>Plate format:</b><br>A123BC 45",
    "<b>Формат номера:</b><br>АВ 1234 СТ": "<b>Plate format:</b><br>AB 1234 CT",
    "<font color='#fbc02d'>Пострадавший</font>": "<font color='#fbc02d'>Injured</font>",
    "Cтарт": "Start",
    "E-mail не соответствует формату: \\": "Email doesn't match the format: \\",
    "Ford Transit СМИ ": "Ford Transit Media ",
    "Ford Transit Скорая": "Ford Transit Ambulance",
    "Ford Инкассация": "Ford Armored Truck",
    "GOLD VIP ( 15 дней )": "GOLD VIP (15 days)",
    "GOLD VIP ( 7 дней )": "GOLD VIP (7 days)",
    "Gold VIP\\n( 1 день )": "Gold VIP\\n(1 day)",
    "Gold VIP\\n( 15 дней )": "Gold VIP\\n(15 days)",
    "Gold VIP\\n( 30 дней )": "Gold VIP\\n(30 days)",
    "Gold VIP\\n( 7 дней )": "Gold VIP\\n(7 days)",
    "JBL Колонка": "JBL Speaker",
    "LADA Priora МВД": "LADA Priora Police",
    "MAN Пожарный": "MAN Fire Truck",
    "Mercedes-Benz c63 МВД": "Mercedes-Benz C63 Police",
    "Mercedes-Benz c63 ФСБ": "Mercedes-Benz C63 FSB",
    "Mercedes-Benz Бензовоз": "Mercedes-Benz Fuel Truck",
    "Mercedes-Benz Мусоровоз": "Mercedes-Benz Garbage Truck",
    "Mercedes-Benz Эвакуатор": "Mercedes-Benz Tow Truck",
    "PLATINUM VIP ( 15 дней )": "PLATINUM VIP (15 days)",
    "PLATINUM VIP ( 30 дней )": "PLATINUM VIP (30 days)",
    "Platinum VIP\\n( 1 день )": "Platinum VIP\\n(1 day)",
    "Platinum VIP\\n( 15 дней )": "Platinum VIP\\n(15 days)",
    "Platinum VIP\\n( 30 дней )": "Platinum VIP\\n(30 days)",
    "Platinum VIP\\n( 7 дней )": "Platinum VIP\\n(7 days)",
    "SILVER VIP ( 7 дней )": "SILVER VIP (7 days)",
    "Silver VIP ( 7 дней )": "Silver VIP (7 days)",
    "Silver VIP\\n( 1 день )": "Silver VIP\\n(1 day)",
    "Silver VIP\\n( 15 дней )": "Silver VIP\\n(15 days)",
    "Silver VIP\\n( 30 дней )": "Silver VIP\\n(30 days)",
    "Silver VIP\\n( 7 дней )": "Silver VIP\\n(7 days)",
    "Skoda Octavia МВД": "Skoda Octavia Police",
    "Автомобили": "Vehicles",
    "Автоугонщик": "Car Thief",
    "Агент 007": "Agent 007",
    "Адвокатура": "Attorney",
    "Админ": "Admin",
    "Аист": "Stork",
    "Алая ведьма": "Scarlet Witch",
    "Алкаш": "Drunkard",
    "Амиран": "Amiran",
    "Анимации": "Animations",
    "Аниме тян": "Anime Girl",
    "Аукционер": "Auctioneer",
    "БИТА": "BAT",
    "БРОНЕЖИЛЕТ": "BODY ARMOR",
    "Баланс: %s LC": "Balance: %s LC",
    "Белая дамская сумка": "White Handbag",
    "Белая маска": "White Mask",
    "Белый рюкзак Adidas": "White Adidas Backpack",
    "Бизнесс": "Business",
    "Богемный": "Bohemian",
    "Бодров": "Bodrov",
    "Божественный Нимб": "Divine Halo",
    "Бригада": "Crew",
    "Бронированный": "Armored",
    "Бульдозер": "Bulldozer",
    "Бустер": "Booster",
    "Буханка": "Buhanka",
    "В БОЛЬНИЦУ": "TO HOSPITAL",
    "Ваш уровень работника: %d": "Your worker level: %d",
    "Ваш экран не поддерживает значение выше %.0f": "Your screen doesn't support a value higher than %.0f",
    "Ваши очки: %d": "Your points: %d",
    "Введите E-mail": "Enter email",
    "Введите никнейм": "Enter nickname",
    "Введите пароль": "Enter password",
    "Введите пароль, чтобы войти в игру.": "Enter password to log into the game.",
    "Введите сумму доната": "Enter donation amount",
    "Ведущий": "Host",
    "Ведьма": "Witch",
    "Винил #$index": "Vinyl #$index",
    "Винилы": "Vinyls",
    "Вихрь удачи": "Whirl of Luck",
    "Вован": "Vovan",
    "Водитель автобуса": "Bus Driver",
    "Военный билет": "Military ID",
    "Войти": "Log In",
    "Волга": "Volga",
    "Волга 3102": "Volga 3102",
    "Ворон": "Raven",
    "Вражеские очки: %d": "Enemy points: %d",
    "Все лицензии": "All Licenses",
    "Вселенский": "Universal",
    "Вы были <font color='#fbc02d'>ранены</font>": "You were <font color='#fbc02d'>injured</font>",
    "Вы были <font color='#fbc02d'>ранены</font> игроком": "You were <font color='#fbc02d'>injured</font> by player",
    "Вы выиграли": "You won",
    "Вы проиграли": "You lost",
    "Вы успешно сбросили настройки!": "You successfully reset the settings!",
    "Выберите сервер": "Choose a server",
    "Выберите способ авторизации!": "Choose a login method!",
    "Выдай 5/10/15 лицензий": "Issue 5/10/15 licenses",
    "Выдать 5/15/50 медкарт": "Issue 5/15/50 medical cards",
    "Выезд на помощь пострадавшим: 15/50/100": "Respond to help victims: 15/50/100",
    "Выиграй в игре кости: 10000/1000000/10000000 рублей": "Win at dice: 10,000/1,000,000/10,000,000 rubles",
    "Выиграй: 100/1000/5000 фишек": "Win: 100/1000/5000 chips",
    "Вылечить: 5/15/50 гражданских лиц": "Heal: 5/15/50 civilians",
    "Выписать 5/10/15 штрафов": "Issue 5/10/15 fines",
    "Выполнено: %d из %d": "Completed: %d of %d",
    "Выполни 10/50/100 заказов": "Complete 10/50/100 orders",
    "Выполни 10/50/100 рейсов": "Complete 10/50/100 trips",
    "Высокая загруженность": "High Load",
    "Высота подвески": "Suspension Height",
    "ГАЗ Хлеб": "GAZ Bread Van",
    "ГОЛЬФ КЛЮШКА": "GOLF CLUB",
    "Газ Чайка": "Gaz Chaika",
    "Газель ВТБ24": "Gazelle VTB24",
    "Газон": "Gazon",
    "Гамора": "Gamora",
    "Гитара": "Guitar",
    "Главный на дороге": "King of the Road",
    "Главный нарушитель": "Chief Offender",
    "Госпошлина %s рублей": "State fee %s rubles",
    "Гуманоид": "Humanoid",
    "Гурман": "Gourmet",
    "ДЫМОВАЯ ШАШКА": "SMOKE GRENADE",
    "Давидыч": "Davidych",
    "Дальнобойщик": "Trucker",
    "Дата окончания: $formattedDate": "Expiration date: $formattedDate",
    "Дафна": "Daphne",
    "Дед Мороз": "Santa Claus",
    "Действия": "Actions",
    "Детстроук": "Deathstroke",
    "Джейсон Вурхиз": "Jason Voorhees",
    "Димитреску": "Dimitrescu",
    "Диски 1": "Rims 1", "Диски 10": "Rims 10", "Диски 11": "Rims 11", "Диски 12": "Rims 12",
    "Диски 13": "Rims 13", "Диски 14": "Rims 14", "Диски 15": "Rims 15", "Диски 16": "Rims 16",
    "Диски 17": "Rims 17", "Диски 2": "Rims 2", "Диски 3": "Rims 3", "Диски 4": "Rims 4",
    "Диски 5": "Rims 5", "Диски 6": "Rims 6", "Диски 7": "Rims 7", "Диски 8": "Rims 8", "Диски 9": "Rims 9",
    "Длина E-mail должна быть меньше 100 символов": "Email length must be less than 100 characters",
    "Длина никнейма должна быть меньше 20 символов": "Nickname length must be less than 20 characters",
    "Длина пароля должна быть больше 5 символов": "Password length must be more than 5 characters",
    "Длина пароля должна быть меньше 17 символов": "Password length must be less than 17 characters",
    "Для начала игры заполните все поля": "Fill in all fields to start the game",
    "Для применения безграничности экрана необходимо перезайти в игру": "To apply borderless screen, you need to re-enter the game",
    "До конца раунда: %d": "Time left in round: %d",
    "До обновления заданий: $formattedTime": "Until tasks refresh: $formattedTime",
    "Доктор": "Doctor",
    "Доминик Торетто": "Dominic Toretto",
    "Донат": "Donation",
    "Доставить 5000/25000/100000 материалов": "Deliver 5000/25000/100000 materials",
    "Доставить на склад ОПГ 1000/5000/15000 материалов": "Deliver 1000/5000/15000 materials to the gang warehouse",
    "Доставщик еды": "Food Courier",
    "Достигни 10/50/100 лвл механика": "Reach mechanic level 10/50/100",
    "Достигни 10/50/100 лвл шахтера": "Reach miner level 10/50/100",
    "Достигни 10/50/100 побед": "Reach 10/50/100 wins",
    "Достигни 10/50/100 уровня автоугонщика": "Reach car thief level 10/50/100",
    "Достигни: 10/50/100 lvl рабочего": "Reach worker level 10/50/100",
    "Достигни: 1000/5000/15000 зависимости": "Reach 1000/5000/15000 addiction",
    "Достигни: 15/50/100 lvl": "Reach level 15/50/100",
    "Достигни: 15/50/100 lvl рабочего": "Reach worker level 15/50/100",
    "Достижения": "Achievements",
    "Доступно через $timeRemaining": "Available in $timeRemaining",
    "Доступно через $timeleft": "Available in $timeleft",
    "Доступно: %s LC": "Available: %s LC",
    "Дуэлянт": "Duelist",
    "Ева": "Eve",
    "Егор Крид": "Egor Kreed",
    "Жалоба": "Complaint",
    "Жёлто-красная сумка": "Yellow-Red Bag",
    "Жёлтый рюкзак Nike": "Yellow Nike Backpack",
    "ЗАЗ 968": "ZAZ 968",
    "Забивной": "Goal Scorer",
    "Забрать": "Collect",
    "Задний": "Rear",
    "Законопослушность +%d": "Law-Abiding Score +%d",
    "Законопослушность\\n( + 10 )": "Law-Abiding Score\\n(+10)",
    "Законопослушный гражданин": "Law-Abiding Citizen",
    "Закрыть": "Close",
    "Заправщик": "Gas Station Worker",
    "Заправь 1.000/5.000/10.000 литров": "Refuel 1,000/5,000/10,000 liters",
    "Заработай 10.000/1.000.000/10.000.000 рублей": "Earn 10,000/1,000,000/10,000,000 rubles",
    "Заработано: %s": "Earned: %s",
    "Заработано: %s рублей": "Earned: %s rubles",
    "Заработано: 0 рублей": "Earned: 0 rubles",
    "Зачарованный": "Enchanted",
    "Защитник Родины": "Defender of the Motherland",
    "Зелье Божества": "Potion of the Deity",
    "Зелье инфернала": "Infernal Potion",
    "Зелье исцеления": "Healing Potion",
    "Зелье мудрости": "Potion of Wisdom",
    "Зелье репутации": "Reputation Potion",
    "Зелье сильфиды": "Sylph Potion",
    "Зелье сытости": "Satiety Potion",
    "Зелёная дамская сумка": "Green Handbag",
    "Зелёная кепка": "Green Cap",
    "Зелёно-синяя сумка": "Green-Blue Bag",
    "Зелёный рюкзак Louis Vuitton": "Green Louis Vuitton Backpack",
    "Золото": "Gold",
    "Золотые руки": "Golden Hands",
    "Зёлная маска 2": "Green Mask 2",
    "Иван Золо": "Ivan Zolo",
    "Игра успешно установлена, введите свой никнейм": "Game successfully installed, enter your nickname",
    "Игра успешно установлена, выберите сервер": "Game successfully installed, choose a server",
    "Игроки": "Players",
    "Изменить имя семьи": "Change Family Name",
    "Иметь 100/500/1000 законопослушности": "Have 100/500/1000 law-abiding score",
    "Инвентарь": "Inventory",
    "Инкассатор": "Cash Collector",
    "Инфернал": "Infernal",
    "Информация: если этот аккаунт является не вашим, то выйдите из игры и смените игровое имя на новое!": "Notice: if this account isn't yours, log out of the game and change your in-game name!",
    "К оплате: %s руб.": "To pay: %s rub.",
    "К получению: %s руб.": "To receive: %s rub.",
    "КАЗ": "KAZ",
    "КАСТЕТ": "BRASS KNUCKLES",
    "КАТАНА": "KATANA",
    "Кавказец": "Caucasian Man",
    "Камаз ОМОН": "Kamaz OMON",
    "Камаз ФСБ": "Kamaz FSB",
    "Камуфляжная кепка": "Camo Cap",
    "Карнавал": "Carnival",
    "Каха": "Kakha",
    "Квадроцикл": "ATV",
    "Кварц": "Quartz",
    "Квин": "Quinn",
    "Кевин Один Дома": "Kevin Home Alone",
    "Кизару": "Kizaru",
    "Кирка": "Pickaxe",
    "Ключ в подземелье": "Key to the Dungeon",
    "Ключ от сундука": "Chest Key",
    "Колокольчик": "Bell",
    "Колонка JBL": "JBL Speaker",
    "Комплект лицензий": "License Set",
    "Комфорт": "Comfort",
    "Конор Макгрегор": "Conor McGregor",
    "Коричневая гитара": "Brown Guitar",
    "Коричневая кепка": "Brown Cap",
    "Коса Баланара": "Balanar's Scythe",
    "Красная дамская сумка": "Red Handbag",
    "Красно-голубая сумка": "Red-Blue Bag",
    "Красно-чёрная сумка": "Red-Black Bag",
    "Красный рюкзак": "Red Backpack",
    "Красный рюкзак Adidas": "Red Adidas Backpack",
    "Красный рюкзак Louis Vuitton": "Red Louis Vuitton Backpack",
    "Крик": "Scream",
    "Кристалл": "Crystal",
    "Крупье: %s[%d]": "Dealer: %s[%d]",
    "Крупье: --": "Dealer: --",
    "Крылья": "Wings",
    "Крюгер": "Krueger",
    "Кузов (1)": "Body (1)",
    "Кузов (2)": "Body (2)",
    "Купить фишки": "Buy Chips",
    "Лазурная кепка": "Azure Cap",
    "Лазурно-розовая сумка": "Azure-Pink Bag",
    "Лазурный рюкзак с розами": "Azure Backpack with Roses",
    "Легендарный": "Legendary",
    "Лепила": "Medic",
    "Лесоруб": "Lumberjack",
    "Ликвидировать 10/50/100 участников ОПГ": "Eliminate 10/50/100 gang members",
    "Литвин": "Litvin",
    "Лицензиат": "Licensor",
    "Лудоман": "Gambler",
    "Лунный рыцарь": "Moon Knight",
    "МАЗ": "MAZ",
    "Маска": "Mask",
    "Маска Payday": "Payday Mask",
    "Маска Гиены": "Hyena Mask",
    "Маска Грызуна": "Rodent Mask",
    "Маска Кабана": "Boar Mask",
    "Маска Кабуки": "Kabuki Mask",
    "Маска Мишки": "Bear Mask",
    "Маска Оленя": "Deer Mask",
    "Маска Пакет": "Bag Mask",
    "Маска Смайла": "Smiley Mask",
    "Мебельщик": "Furniture Maker",
    "Мед. карта": "Medical Card",
    "Медь": "Copper",
    "Меню": "Menu",
    "Месси": "Messi",
    "Металоискатель": "Metal Detector",
    "Механик": "Mechanic",
    "Меценат": "Patron",
    "Меч Саурона": "Sword of Sauron",
    "Милохин": "Milokhin",
    "Мифический": "Mythical",
    "Мияги": "Miyagi",
    "Молот Тора": "Thor's Hammer",
    "Мопед Вятка": "Vyatka Moped",
    "Моргающий": "Blinking",
    "Моргенштерн": "Morgenshtern",
    "Морталкомбат маска": "Mortal Kombat Mask",
    "Москвич 149": "Moskvich 149",
    "Мужик": "Dude",
    "Мусоровоз": "Garbage Truck",
    "На пути к миллионам": "On the Way to Millions",
    "Навигатор": "Navigator",
    "Наешься до блевоты 5/10/15 раз": "Eat until you vomit 5/10/15 times",
    "Нажмите, чтобы войти": "Tap to log in",
    "Напиться до головокружения 5/10/15 раз": "Get drunk to the point of dizziness 5/10/15 times",
    "Настройки по умолчанию уже установлены": "Default settings are already set",
    "Не более 4-х сообщений!": "No more than 4 messages!",
    "Не больше 400 символов!": "No more than 400 characters!",
    "Не смогли проверить что вы не робот, попробуйте еще раз": "Couldn't verify you're not a robot, please try again",
    "Не удалось загрузить данные": "Failed to load data",
    "Не указан": "Not specified",
    "Недоступно": "Unavailable",
    "Неизвестно": "Unknown",
    "Неймар": "Neymar",
    "Некоглай": "Nekoglai",
    "Необычный": "Uncommon",
    "Нет винила": "No vinyl",
    "Нет данных о игроках": "No player data",
    "Нет неона": "No neon",
    "Нет ничего важнее семьи": "Nothing is more important than family",
    "Нет стробоскопа": "No strobe",
    "Нефтяник": "Oil Worker",
    "Низкая загруженность": "Low Load",
    "Никнейм не должен содержать цифр": "Nickname must not contain digits",
    "Никнейм не соответствует формату: \\": "Nickname doesn't match the format: \\",
    "Ничья": "Draw",
    "Обжора": "Glutton",
    "Обработать 100/500/1000 репортов (/rep)": "Process 100/500/1000 reports (/rep)",
    "Общение": "Communication",
    "Обычный": "Common",
    "Оксимирон": "Oxxxymiron",
    "Оранжевая дамская сумка": "Orange Handbag",
    "Оружейник": "Gunsmith",
    "Освободить из под стражи: 5/10/15 гражданских лиц": "Release from custody: 5/10/15 civilians",
    "Основное": "Main",
    "Ответить на 100/500/1000 вопросов (/ask)": "Answer 100/500/1000 questions (/ask)",
    "Открой 5/50/150 контейнер": "Open 5/50/150 containers",
    "Открой: 3/10/50 сундуков в рулетке": "Open 3/10/50 chests in roulette",
    "Отредактировать: 10/50/100 объявлений": "Edit 10/50/100 ads",
    "Охра": "Ochre",
    "Ошибка установки: файл не найден": "Installation error: file not found",
    "ПАЗ": "PAZ",
    "Пабло": "Pablo",
    "Палпатин": "Palpatine",
    "Пароль для тестового севрера не был задан": "Password for the test server was not set",
    "Пацан": "Kid",
    "Пейнтбольная маска": "Paintball Mask",
    "Пеннивайз": "Pennywise",
    "Перевези 100/500/1000 мешков с деньгами": "Transport 100/500/1000 bags of money",
    "Переверни 10/50/100 машин": "Flip 10/50/100 cars",
    "Перевозчик": "Carrier",
    "Перевёртыш": "Flipper",
    "Перед входом подтвердите что вы не робот": "Confirm you're not a robot before entering",
    "Перед подключением к серверу введите никнейм": "Enter your nickname before connecting to the server",
    "Передача семьи": "Family Transfer",
    "Передний": "Front",
    "Переливающийся": "Shimmering",
    "Перемещено": "Moved",
    "Переустановить игру?": "Reinstall the game?",
    "Пивозаворка": "Beer Runner",
    "Пивозавр": "Beerosaurus",
    "Победить в бизваре: 5/50/100 раз": "Win in Biz War: 5/50/100 times",
    "Победить в танковых боях: 1/5/10 раз": "Win in tank battles: 1/5/10 times",
    "Победить на семейных захватах 5/50/100 раз": "Win family takeovers 5/50/100 times",
    "Подача: $formattedDistance (~$formattedTime)": "Delivery: $formattedDistance (~$formattedTime)",
    "Подключение к последнему выбранному серверу!": "Connecting to the last selected server!",
    "Подключение к серверу: %s!": "Connecting to server: %s!",
    "Подтвердите установку": "Confirm installation",
    "Поездок: %d": "Trips: %d",
    "Пожертвовать в благотворительность 20000/500000/5000000": "Donate 20000/500000/5000000 to charity",
    "Полицейский": "Police Officer",
    "Полный": "Full",
    "Положить в общак: 50/150/500 аптечек": "Put 50/150/500 first-aid kits into the gang stash",
    "Положить в общак: 50/150/500 бронежилетов": "Put 50/150/500 body armors into the gang stash",
    "Получено": "Received",
    "Получите 3/6/9 звезд розыска за один раз в игре": "Get 3/6/9 wanted stars at once",
    "Посох": "Staff",
    "Поступило предложение": "An offer has been received",
    "Потрать 10.000/1.000.000/10.000.000 рублей": "Spend 10,000/1,000,000/10,000,000 rubles",
    "Почини 10/50/100 машин": "Repair 10/50/100 cars",
    "Прицеп 1": "Trailer 1",
    "Прицеп_2": "Trailer_2",
    "Проведи в игре 10/100/1000 часов": "Spend 10/100/1000 hours in the game",
    "Провести 5/10/25 арестов": "Make 5/10/25 arrests",
    "Провести: 1/3/5 эфиров": "Host 1/3/5 livestreams",
    "Продать фишки": "Sell Chips",
    "Проехать 10.000/100.000/1.000.000 км на любом транспорте": "Drive 10,000/100,000/1,000,000 km in any vehicle",
    "Прокрути колесо удачи: 5/15/50 раз": "Spin the wheel of fortune: 5/15/50 times",
    "Промокод": "Promo Code",
    "Проставки": "Spacers",
    "Прян": "Pryan",
    "Путешественник": "Traveler",
    "Путник": "Wanderer",
    "Пёсель": "Doggo",
    "Радиус диска": "Rim Radius",
    "Развал-схождение (зад)": "Wheel Alignment (rear)",
    "Развал-схождение (перед)": "Wheel Alignment (front)",
    "Ракета": "Rocket",
    "Распаковка ...": "Unpacking ...",
    "Распаковка завершена: ${from}": "Unpacking complete: ${from}",
    "Редакция": "Editorial",
    "Редкий": "Rare",
    "Редкость: %s": "Rarity: %s",
    "Режим 2": "Mode 2",
    "Режим 3": "Mode 3",
    "Режим 4": "Mode 4",
    "Резкий": "Sharp",
    "Рекомендуемый тип топлива: АИ-100": "Recommended fuel type: AI-100",
    "Рекомендуемый тип топлива: АИ-92": "Recommended fuel type: AI-92",
    "Рекомендуемый тип топлива: АИ-95": "Recommended fuel type: AI-95",
    "Рекомендуемый тип топлива: АИ-98": "Recommended fuel type: AI-98",
    "Рекомендуемый тип топлива: ДТ": "Recommended fuel type: Diesel",
    "Респиратор": "Respirator",
    "Розовая дамская сумка": "Pink Handbag",
    "Розово-леопардовая сумка": "Pink Leopard Bag",
    "Розовый рюкзак": "Pink Backpack",
    "Ролики": "Roller Skates",
    "Ролики ( анимация ходьбы )": "Roller Skates (walking animation)",
    "Роналду": "Ronaldo",
    "Руда": "Ore",
    "Саппорт": "Support",
    "Сбросить настройки игры?": "Reset game settings?",
    "Северус": "Severus",
    "Семья": "Family",
    "Серая широкая маска": "Wide Gray Mask",
    "Сервер выбран! Для начала игры нажмите жёлтую кнопку": "Server selected! Press the yellow button to start the game",
    "Серго": "Sergo",
    "Сильфида": "Sylph",
    "Сине-розовая сумка": "Blue-Pink Bag",
    "Сине-чёрная сумка": "Blue-Black Bag",
    "Синий рюкзак": "Blue Backpack",
    "Синяя дамская сумка": "Blue Handbag",
    "Скачали файл ${fileInfo.path}": "Downloaded file ${fileInfo.path}",
    "Скейт": "Skateboard",
    "Скейтборд": "Skateboard",
    "Скейтборд Hoopla": "Hoopla Skateboard",
    "Скейтборд Rise & Shine": "Rise & Shine Skateboard",
    "Скейтборд Tony Hawk": "Tony Hawk Skateboard",
    "Скейтборд обычный": "Regular Skateboard",
    "Скелетон": "Skeleton",
    "Скин $skinId": "Skin $skinId",
    "Скопированно в буфер обмена ": "Copied to clipboard ",
    "Славянин": "Slav",
    "Слот для Бизнеса": "Business Slot",
    "Слот для авто": "Vehicle Slot",
    "Слот для бизнеса": "Business Slot",
    "Слот для дома": "House Slot",
    "Слот для дома\\n(От 1000)": "House Slot\\n(From 1000)",
    "Слот для семейного авто": "Family Vehicle Slot",
    "Случайное оружие ( 1.000 пт)": "Random Weapon (1,000 pts)",
    "Случайный вариант \\nза %s руб.": "Random option\\nfor %s rub.",
    "Смена дисков": "Change Rims",
    "Смена ника": "Change Nickname",
    "Смена пола": "Change Gender",
    "Сначала дешевые": "Cheapest First",
    "Сначала дорогие": "Most Expensive First",
    "Сначала загрузите игру!": "Download the game first!",
    "Сначала новые": "Newest First",
    "Сначала установите игру": "Install the game first",
    "Снегоуборочная машина": "Snowplow",
    "Снегоход": "Snowmobile",
    "Снегурочка": "Snow Maiden",
    "Снятие Warn'a": "Removing a Warn",
    "Снятие варна": "Removing a Warn",
    "Снять варн": "Remove Warn",
    "Соверши 10/100/1000 убийств на ДМ арене": "Get 10/100/1000 kills on the DM arena",
    "Содержимое файлов валидно!": "File contents are valid!",
    "Солнцезащитные очки": "Sunglasses",
    "Солнцезащитные очки 2": "Sunglasses 2",
    "Солнцезащитные очки 3": "Sunglasses 3",
    "Сорвать куш": "Hit the Jackpot",
    "Сорвиголова": "Daredevil",
    "Средняя загруженность": "Medium Load",
    "Старожил": "Old-Timer",
    "Статичный цвет": "Static Color",
    "Стоковые": "Stock",
    "Стол $tableID": "Table $tableID",
    "Страж порядка": "Guardian of Order",
    "Стрелок (общий режим)": "Shooter (general mode)",
    "Стробоскопы": "Strobes",
    "Сумка Луи": "Louis Bag",
    "Сумка Рич": "Rich Bag",
    "Сумма доната не должна содержать ничего кроме цифр": "Donation amount must contain only digits",
    "Сундукопроныр": "Chest Raider",
    "Супергерой": "Superhero",
    "Сход-развал (зад.)": "Wheel Alignment (rear)",
    "Сход-развал (перед.)": "Wheel Alignment (front)",
    "Танк": "Tank",
    "Танкист": "Tanker",
    "Тариф: %s": "Rate: %s",
    "Тигр Военный": "Military Tiger",
    "Тип неона": "Neon Type",
    "Тканевая маска": "Cloth Mask",
    "Топор Этригана": "Etrigan's Axe",
    "Торчок": "Junkie",
    "Трактор": "Tractor",
    "Трезубец Сулимо": "Sulimo's Trident",
    "Трудоголик": "Workaholic",
    "Тыква": "Pumpkin",
    "УАЗ - Патриот": "UAZ Patriot",
    "УАЗ-452": "UAZ-452",
    "УАЗ-452 Военный": "UAZ-452 Military",
    "Уголь": "Coal",
    "Удаление файла: ${file.path}": "Deleting file: ${file.path}",
    "Удалено": "Deleted",
    "Укажите ник!": "Specify a nickname!",
    "Улучшенный": "Improved",
    "Урал 4320": "Ural 4320",
    "Уровень $myLvl": "Level $myLvl",
    "Установите поворот": "Set rotation",
    "Установите размер": "Set size",
    "Установите смещение по оси X": "Set X-axis offset",
    "Установите смещение по оси Y": "Set Y-axis offset",
    "Установите смещение по оси Z": "Set Z-axis offset",
    "Файлы в порядке!": "Files are OK!",
    "Фиолетовый рюкзак PUMA": "Purple PUMA Backpack",
    "Флеш": "Flash",
    "Форсаж": "Fast & Furious",
    "Фортуна": "Fortune",
    "Хабиб": "Khabib",
    "Харли": "Harley",
    "Цвет дисков": "Rim Color",
    "Цвет неона": "Neon Color",
    "Цвет тонера": "Tint Color",
    "Цвет фар": "Headlight Color",
    "Целитель сердец": "Healer of Hearts",
    "Цепной": "Chained",
    "Человек Паук": "Spider-Man",
    "Чёрная гитара": "Black Guitar",
    "Чёрная дамская сумка": "Black Handbag",
    "Чёрная сумка": "Black Bag",
    "Чёрные очки": "Black Glasses",
    "Чёрный рюкзак": "Black Backpack",
    "Чёрный рюкзак с розами": "Black Backpack with Roses",
    "Шахтёр": "Miner",
    "Ширина резины": "Tire Width",
    "Ширина шин": "Tire Width",
    "Школьница": "Schoolgirl",
    "Шопоголик": "Shopaholic",
    "Шрек": "Shrek",
    "Щит Капитана Америки": "Captain America's Shield",
    "Эвакуаторщик": "Tow Truck Driver",
    "Эвакуируй на штрафстоянку 10/50/100 машин": "Tow 10/50/100 cars to the impound lot",
    "Эконом": "Economy",
    "Элит": "Elite",
    "Ювелир": "Jeweler",
    "бесплатная прокрутка": "free spin",
    "купить": "buy",
    "от %s руб.": "from %s rub.",
    "продать": "sell",
    "сиджей": "CJ",
}

def main():
    changed_files = 0
    changed_strings = 0
    for dirpath, _, filenames in os.walk(ROOT):
        for fname in filenames:
            if not (fname.endswith(".kt") or fname.endswith(".java")):
                continue
            fpath = os.path.join(dirpath, fname)
            with open(fpath, encoding="utf-8") as f:
                content = f.read()
            original = content
            file_hits = 0
            # Replace longer strings first to avoid partial-match issues
            for ru in sorted(TRANSLATIONS.keys(), key=len, reverse=True):
                en = TRANSLATIONS[ru]
                count = content.count(ru)
                if count:
                    content = content.replace(ru, en)
                    file_hits += count
            if content != original:
                with open(fpath + ".bak", "w", encoding="utf-8") as f:
                    f.write(original)
                with open(fpath, "w", encoding="utf-8") as f:
                    f.write(content)
                changed_files += 1
                changed_strings += file_hits
                print(f"Updated {fpath} ({file_hits} strings)")
    print(f"\nDone. {changed_files} files changed, {changed_strings} strings translated.")
    print("Backups saved as *.bak next to each changed file.")

if __name__ == "__main__":
    main()
